### ISSUE TITLE
Errors management

### ISSUE THREAD

**Issue by Gyoo** [Gyoo/LiveSplit.SplitsBet#22]
While in alpha/beta, I think it'd be useful to have some logging of some sort. I know that Livesplit has a log somewhere, but I don't know how it'd handle the plugin if it does some errors.
Also, the streamer may not have any way to acknowledge that there has been errors. How about a custom exception that sends a message to the chat whenever something wrong happens ? (If it's possible)

**Comment by 0x0ade** [comment]
Is a more verbose or a more elegant (whole stack trace in chat vs warning in chat and stack trace in file) method the favored one?

**Comment by Gyoo** [comment]
I'd say, just a notification in chat, and verbose in logs. Sounds good.

**Comment by 0x0ade** [comment]
I don't know if I should simply use LiveSplit.Options.Log as it prints its errors into the Event Log (needs an environment variable in Linux, which also explains why I didn't see any errors while launching LS via Mono; accessible via Control Panel in Windows), use the Event Log with another source than the default LiveSplit or create a text file and log into it. What's your opinion about this?
