### ISSUE TITLE
Allow handling of exterior commands without showing errors

### ISSUE THREAD

**Issue by Gyoo** [Gyoo/LiveSplit.SplitsBet#30]
If someone has Nightbot with custom commands, SplitsBet alerts that there's an error because of a command that is not in its list. It shouldn't show an error (Just hide the message maybe ?)

**Comment by szong** [comment]
Alerts from Twitch chat (as in, it sends a message)? If so, should just be a couple-line comment out.

Otherwise, if it's a program block, the null check should just return.

**Comment by Gyoo** [comment]
Yes. It should be really easy to fix, but I'm falling asleep on my keyboard so I just noted that it has to be done.
